from unittest.mock import Mock

import pytest

from edgework.clients.player_client import PlayerClient
from edgework.models.player import Player


@pytest.fixture
def mock_http_client():
    return Mock()


@pytest.fixture
def player_client(mock_http_client):
    return PlayerClient(mock_http_client)


def test_get_player(player_client, mock_http_client):
    mock_response = Mock()
    mock_response.json.return_value = {"playerId": 8478402, "isActive": True, "currentTeamId": 22,
                                       "currentTeamAbbrev": "EDM",
                                       "fullTeamName": {"default": "Edmonton Oilers", "fr": "Oilers d'Edmonton"},
                                       "teamCommonName": {"default": "Oilers"},
                                       "teamPlaceNameWithPreposition": {"default": "Edmonton", "fr": "d'Edmonton"},
                                       "firstName": {"default": "Connor"}, "lastName": {"default": "McDavid"},
                                       "teamLogo": "https://assets.nhle.com/logos/nhl/svg/EDM_light.svg",
                                       "sweaterNumber": 97, "position": "C",
                                       "headshot": "https://assets.nhle.com/mugs/nhl/20242025/EDM/8478402.png",
                                       "heroImage": "https://assets.nhle.com/mugs/actionshots/1296x729/8478402.jpg",
                                       "heightInInches": 73, "heightInCentimeters": 185, "weightInPounds": 194,
                                       "weightInKilograms": 88, "birthDate": "1997-01-13",
                                       "birthCity": {"default": "Richmond Hill"},
                                       "birthStateProvince": {"default": "Ontario"}, "birthCountry": "CAN",
                                       "shootsCatches": "L",
                                       "draftDetails": {"year": 2015, "teamAbbrev": "EDM", "round": 1, "pickInRound": 1,
                                                        "overallPick": 1}, "playerSlug": "connor-mcdavid-8478402",
                                       "inTop100AllTime": 0, "inHHOF": 0,
                                       "shopLink": "#TODO",
                                       "twitterLink": "#TODO",
                                       "seasonTotals": [
                                           {"assists": 7, "gameTypeId": 2, "gamesPlayed": 7, "goals": 7,
                                            "leagueAbbrev": "QC Int PW", "pim": 0,
                                            "points": 14, "season": 20082009, "sequence": 315272,
                                            "teamName": {"default": "York Simcoe Peewee"}},
                                           {"assists": 50, "gameTypeId": 2, "gamesPlayed": 33, "goals": 27,
                                            "leagueAbbrev": "GTHL", "points": 77,
                                            "season": 20112012, "sequence": 1,
                                            "teamName": {"default": "Tor. Marlboros"}},
                                           {"assists": 65, "gameTypeId": 2, "gamesPlayed": 41, "goals": 41,
                                            "leagueAbbrev": "Other", "points": 106,
                                            "season": 20112012, "sequence": 2,
                                            "teamName": {"default": "Tor. Marlboros"}},
                                           {"assists": 32, "gameTypeId": 2, "gamesPlayed": 17, "goals": 31,
                                            "leagueAbbrev": "Other", "points": 63,
                                            "season": 20112012, "sequence": 3, "teamName": {"default": "PEAC"}},
                                           {"assists": 15, "gameTypeId": 3, "gamesPlayed": 14, "goals": 11,
                                            "leagueAbbrev": "GTHL", "points": 26,
                                            "season": 20112012, "sequence": 1,
                                            "teamName": {"default": "Tor. Marlboros"}},
                                           {"assists": 41, "gameTypeId": 2, "gameWinningGoals": 2, "gamesPlayed": 63,
                                            "goals": 25,
                                            "leagueAbbrev": "OHL", "pim": 36, "plusMinus": -24, "points": 66,
                                            "powerPlayGoals": 2, "season": 20122013,
                                            "sequence": 1, "shorthandedGoals": 1, "teamName": {"default": "Erie"}},
                                           {"assists": 6, "gameTypeId": 2, "gameWinningGoals": 2, "gamesPlayed": 7,
                                            "goals": 8,
                                            "leagueAbbrev": "WJ18-A", "pim": 2, "points": 14, "powerPlayGoals": 5,
                                            "season": 20122013, "sequence": 2,
                                            "shorthandedGoals": 0, "shots": 23,
                                            "teamCommonName": {"default": "Canada", "cs": "Kanada", "de": "Kanada",
                                                               "fi": "Kanada", "sk": "Kanada",
                                                               "sv": "Kanada"},
                                            "teamName": {"default": "Canada", "cs": "Kanada", "de": "Kanada",
                                                         "fi": "Kanada", "sk": "Kanada",
                                                         "sv": "Kanada"}},
                                           {"assists": 71, "gameTypeId": 2, "gameWinningGoals": 4, "gamesPlayed": 56,
                                            "goals": 28,
                                            "leagueAbbrev": "OHL", "pim": 20, "plusMinus": 47, "points": 99,
                                            "powerPlayGoals": 7, "season": 20132014,
                                            "sequence": 1, "shorthandedGoals": 2, "teamName": {"default": "Erie"}},
                                           {"assists": 15, "gameTypeId": 3, "gamesPlayed": 14, "goals": 4,
                                            "leagueAbbrev": "OHL", "pim": 2,
                                            "plusMinus": -1, "points": 19, "powerPlayGoals": 0, "season": 20132014,
                                            "sequence": 1,
                                            "shorthandedGoals": 0, "teamName": {"default": "Erie"}},
                                           {"assists": 76, "gameTypeId": 2, "gameWinningGoals": 8, "gamesPlayed": 47,
                                            "goals": 44,
                                            "leagueAbbrev": "OHL", "pim": 48, "plusMinus": 60, "points": 120,
                                            "powerPlayGoals": 9, "season": 20142015,
                                            "sequence": 1, "shorthandedGoals": 2, "teamName": {"default": "Erie"}},
                                           {"assists": 8, "gameTypeId": 2, "gameWinningGoals": 1, "gamesPlayed": 7,
                                            "goals": 3,
                                            "leagueAbbrev": "WJC-A", "pim": 0, "plusMinus": 8, "points": 11,
                                            "powerPlayGoals": 1, "season": 20142015,
                                            "sequence": 2, "shorthandedGoals": 0, "shots": 21,
                                            "teamCommonName": {"default": "Canada", "cs": "Kanada", "de": "Kanada",
                                                               "fi": "Kanada", "sk": "Kanada",
                                                               "sv": "Kanada"},
                                            "teamName": {"default": "Canada", "cs": "Kanada", "de": "Kanada",
                                                         "fi": "Kanada", "sk": "Kanada",
                                                         "sv": "Kanada"}},
                                           {"assists": 28, "gameTypeId": 3, "gameWinningGoals": 5, "gamesPlayed": 20,
                                            "goals": 21,
                                            "leagueAbbrev": "OHL", "pim": 12, "plusMinus": 12, "points": 49,
                                            "powerPlayGoals": 4, "season": 20142015,
                                            "sequence": 1, "shorthandedGoals": 3, "teamName": {"default": "Erie"}},
                                           {"assists": 32, "avgToi": "18:53", "faceoffWinningPctg": 0.4123,
                                            "gameTypeId": 2, "gameWinningGoals": 5,
                                            "gamesPlayed": 45, "goals": 16, "leagueAbbrev": "NHL", "otGoals": 1,
                                            "pim": 18, "plusMinus": -1,
                                            "points": 48, "powerPlayGoals": 3, "powerPlayPoints": 14,
                                            "season": 20152016, "sequence": 1,
                                            "shootingPctg": 0.1524, "shorthandedGoals": 0, "shorthandedPoints": 0,
                                            "shots": 105,
                                            "teamCommonName": {"default": "Oilers"},
                                            "teamName": {"default": "Edmonton Oilers", "fr": "Oilers d'Edmonton"},
                                            "teamPlaceNameWithPreposition": {"default": "Edmonton",
                                                                             "fr": "d'Edmonton"}},
                                           {"assists": 8, "gameTypeId": 2, "gameWinningGoals": 1, "gamesPlayed": 10,
                                            "goals": 1,
                                            "leagueAbbrev": "WC-A", "pim": 6, "plusMinus": 3, "points": 9,
                                            "powerPlayGoals": 0, "season": 20152016,
                                            "sequence": 2, "shorthandedGoals": 0, "shots": 15,
                                            "teamCommonName": {"default": "Canada", "cs": "Kanada", "de": "Kanada",
                                                               "fi": "Kanada", "sk": "Kanada",
                                                               "sv": "Kanada"},
                                            "teamName": {"default": "Canada", "cs": "Kanada", "de": "Kanada",
                                                         "fi": "Kanada", "sk": "Kanada",
                                                         "sv": "Kanada"}},
                                           {"assists": 70, "avgToi": "21:08", "faceoffWinningPctg": 0.4318,
                                            "gameTypeId": 2, "gameWinningGoals": 6,
                                            "gamesPlayed": 82, "goals": 30, "leagueAbbrev": "NHL", "otGoals": 1,
                                            "pim": 26, "plusMinus": 27,
                                            "points": 100, "powerPlayGoals": 3, "powerPlayPoints": 27,
                                            "season": 20162017, "sequence": 1,
                                            "shootingPctg": 0.1195, "shorthandedGoals": 1, "shorthandedPoints": 2,
                                            "shots": 251,
                                            "teamCommonName": {"default": "Oilers"},
                                            "teamName": {"default": "Edmonton Oilers", "fr": "Oilers d'Edmonton"},
                                            "teamPlaceNameWithPreposition": {"default": "Edmonton",
                                                                             "fr": "d'Edmonton"}},
                                           {"assists": 3, "gameTypeId": 2, "gamesPlayed": 3, "goals": 0,
                                            "leagueAbbrev": "WCup", "pim": 4,
                                            "plusMinus": 1, "points": 3, "season": 20162017, "sequence": 176776,
                                            "teamName": {"default": "Team North America"}},
                                           {"assists": 4, "avgToi": "22:25", "faceoffWinningPctg": 0.3578,
                                            "gameTypeId": 3, "gameWinningGoals": 0,
                                            "gamesPlayed": 13, "goals": 5, "leagueAbbrev": "NHL", "otGoals": 0,
                                            "pim": 2, "plusMinus": 3, "points": 9,
                                            "powerPlayGoals": 1, "powerPlayPoints": 4, "season": 20162017,
                                            "sequence": 1, "shootingPctg": 0.1351,
                                            "shorthandedGoals": 1, "shorthandedPoints": 1, "shots": 37,
                                            "teamCommonName": {"default": "Oilers"},
                                            "teamName": {"default": "Edmonton Oilers", "fr": "Oilers d'Edmonton"},
                                            "teamPlaceNameWithPreposition": {"default": "Edmonton",
                                                                             "fr": "d'Edmonton"}},
                                           {"assists": 67, "avgToi": "21:33", "faceoffWinningPctg": 0.4136,
                                            "gameTypeId": 2, "gameWinningGoals": 7,
                                            "gamesPlayed": 82, "goals": 41, "leagueAbbrev": "NHL", "otGoals": 2,
                                            "pim": 26, "plusMinus": 20,
                                            "points": 108, "powerPlayGoals": 5, "powerPlayPoints": 20,
                                            "season": 20172018, "sequence": 1,
                                            "shootingPctg": 0.1496, "shorthandedGoals": 1, "shorthandedPoints": 4,
                                            "shots": 274,
                                            "teamCommonName": {"default": "Oilers"},
                                            "teamName": {"default": "Edmonton Oilers", "fr": "Oilers d'Edmonton"},
                                            "teamPlaceNameWithPreposition": {"default": "Edmonton",
                                                                             "fr": "d'Edmonton"}},
                                           {"assists": 12, "gameTypeId": 2, "gamesPlayed": 10, "goals": 5,
                                            "leagueAbbrev": "WC", "pim": 10,
                                            "plusMinus": 6, "points": 17, "season": 20172018, "sequence": 17155,
                                            "teamName": {"default": "Canada"}},
                                           {"assists": 75, "avgToi": "22:50", "faceoffWinningPctg": 0.4662,
                                            "gameTypeId": 2, "gameWinningGoals": 9,
                                            "gamesPlayed": 78, "goals": 41, "leagueAbbrev": "NHL", "otGoals": 3,
                                            "pim": 20, "plusMinus": 3,
                                            "points": 116, "powerPlayGoals": 9, "powerPlayPoints": 33,
                                            "season": 20182019, "sequence": 1,
                                            "shootingPctg": 0.1708, "shorthandedGoals": 1, "shorthandedPoints": 2,
                                            "shots": 240,
                                            "teamCommonName": {"default": "Oilers"},
                                            "teamName": {"default": "Edmonton Oilers", "fr": "Oilers d'Edmonton"},
                                            "teamPlaceNameWithPreposition": {"default": "Edmonton",
                                                                             "fr": "d'Edmonton"}},
                                           {"assists": 63, "avgToi": "21:52", "faceoffWinningPctg": 0.4776,
                                            "gameTypeId": 2, "gameWinningGoals": 6,
                                            "gamesPlayed": 64, "goals": 34, "leagueAbbrev": "NHL", "otGoals": 0,
                                            "pim": 28, "plusMinus": -6,
                                            "points": 97, "powerPlayGoals": 11, "powerPlayPoints": 43,
                                            "season": 20192020, "sequence": 1,
                                            "shootingPctg": 0.16, "shorthandedGoals": 0, "shorthandedPoints": 0,
                                            "shots": 212,
                                            "teamCommonName": {"default": "Oilers"},
                                            "teamName": {"default": "Edmonton Oilers", "fr": "Oilers d'Edmonton"},
                                            "teamPlaceNameWithPreposition": {"default": "Edmonton",
                                                                             "fr": "d'Edmonton"}},
                                           {"assists": 4, "avgToi": "22:23", "faceoffWinningPctg": 0.431,
                                            "gameTypeId": 3, "gameWinningGoals": 1,
                                            "gamesPlayed": 4, "goals": 5, "leagueAbbrev": "NHL", "otGoals": 0, "pim": 2,
                                            "plusMinus": 1, "points": 9,
                                            "powerPlayGoals": 3, "powerPlayPoints": 5, "season": 20192020,
                                            "sequence": 1, "shootingPctg": 0.455,
                                            "shorthandedGoals": 0, "shorthandedPoints": 0, "shots": 11,
                                            "teamCommonName": {"default": "Oilers"},
                                            "teamName": {"default": "Edmonton Oilers", "fr": "Oilers d'Edmonton"},
                                            "teamPlaceNameWithPreposition": {"default": "Edmonton",
                                                                             "fr": "d'Edmonton"}},
                                           {"assists": 72, "avgToi": "22:09", "faceoffWinningPctg": 0.4953,
                                            "gameTypeId": 2, "gameWinningGoals": 11,
                                            "gamesPlayed": 56, "goals": 33, "leagueAbbrev": "NHL", "otGoals": 2,
                                            "pim": 20, "plusMinus": 21,
                                            "points": 105, "powerPlayGoals": 9, "powerPlayPoints": 37,
                                            "season": 20202021, "sequence": 1,
                                            "shootingPctg": 0.165, "shorthandedGoals": 0, "shorthandedPoints": 0,
                                            "shots": 200,
                                            "teamCommonName": {"default": "Oilers"},
                                            "teamName": {"default": "Edmonton Oilers", "fr": "Oilers d'Edmonton"},
                                            "teamPlaceNameWithPreposition": {"default": "Edmonton",
                                                                             "fr": "d'Edmonton"}},
                                           {"assists": 3, "avgToi": "30:24", "faceoffWinningPctg": 0.4524,
                                            "gameTypeId": 3, "gameWinningGoals": 0,
                                            "gamesPlayed": 4, "goals": 1, "leagueAbbrev": "NHL", "otGoals": 0, "pim": 0,
                                            "plusMinus": -2, "points": 4,
                                            "powerPlayGoals": 0, "powerPlayPoints": 1, "season": 20202021,
                                            "sequence": 1, "shootingPctg": 0.067,
                                            "shorthandedGoals": 0, "shorthandedPoints": 0, "shots": 15,
                                            "teamCommonName": {"default": "Oilers"},
                                            "teamName": {"default": "Edmonton Oilers", "fr": "Oilers d'Edmonton"},
                                            "teamPlaceNameWithPreposition": {"default": "Edmonton",
                                                                             "fr": "d'Edmonton"}},
                                           {"assists": 79, "avgToi": "22:04", "faceoffWinningPctg": 0.537285,
                                            "gameTypeId": 2, "gameWinningGoals": 9,
                                            "gamesPlayed": 80, "goals": 44, "leagueAbbrev": "NHL", "otGoals": 4,
                                            "pim": 45, "plusMinus": 28,
                                            "points": 123, "powerPlayGoals": 10, "powerPlayPoints": 44,
                                            "season": 20212022, "sequence": 1,
                                            "shootingPctg": 0.14, "shorthandedGoals": 0, "shorthandedPoints": 1,
                                            "shots": 314,
                                            "teamCommonName": {"default": "Oilers"},
                                            "teamName": {"default": "Edmonton Oilers", "fr": "Oilers d'Edmonton"},
                                            "teamPlaceNameWithPreposition": {"default": "Edmonton",
                                                                             "fr": "d'Edmonton"}},
                                           {"assists": 23, "avgToi": "23:02", "faceoffWinningPctg": 0.525714,
                                            "gameTypeId": 3, "gameWinningGoals": 1,
                                            "gamesPlayed": 16, "goals": 10, "leagueAbbrev": "NHL", "otGoals": 1,
                                            "pim": 10, "plusMinus": 15,
                                            "points": 33, "powerPlayGoals": 2, "powerPlayPoints": 8, "season": 20212022,
                                            "sequence": 1,
                                            "shootingPctg": 0.164, "shorthandedGoals": 0, "shorthandedPoints": 1,
                                            "shots": 61,
                                            "teamCommonName": {"default": "Oilers"},
                                            "teamName": {"default": "Edmonton Oilers", "fr": "Oilers d'Edmonton"},
                                            "teamPlaceNameWithPreposition": {"default": "Edmonton",
                                                                             "fr": "d'Edmonton"}},
                                           {"assists": 89, "avgToi": "22:23", "faceoffWinningPctg": 0.519288,
                                            "gameTypeId": 2, "gameWinningGoals": 11,
                                            "gamesPlayed": 82, "goals": 64, "leagueAbbrev": "NHL", "otGoals": 2,
                                            "pim": 36, "plusMinus": 22,
                                            "points": 153, "powerPlayGoals": 21, "powerPlayPoints": 71,
                                            "season": 20222023, "sequence": 1,
                                            "shootingPctg": 0.181818, "shorthandedGoals": 4, "shorthandedPoints": 7,
                                            "shots": 352,
                                            "teamCommonName": {"default": "Oilers"},
                                            "teamName": {"default": "Edmonton Oilers", "fr": "Oilers d'Edmonton"},
                                            "teamPlaceNameWithPreposition": {"default": "Edmonton",
                                                                             "fr": "d'Edmonton"}},
                                           {"assists": 12, "avgToi": "23:43", "faceoffWinningPctg": 0.483444,
                                            "gameTypeId": 3, "gameWinningGoals": 0,
                                            "gamesPlayed": 12, "goals": 8, "leagueAbbrev": "NHL", "otGoals": 0,
                                            "pim": 0, "plusMinus": -1,
                                            "points": 20, "powerPlayGoals": 5, "powerPlayPoints": 12,
                                            "season": 20222023, "sequence": 1,
                                            "shootingPctg": 0.156863, "shorthandedGoals": 1, "shorthandedPoints": 1,
                                            "shots": 51,
                                            "teamCommonName": {"default": "Oilers"},
                                            "teamName": {"default": "Edmonton Oilers", "fr": "Oilers d'Edmonton"},
                                            "teamPlaceNameWithPreposition": {"default": "Edmonton",
                                                                             "fr": "d'Edmonton"}},
                                           {"assists": 100, "avgToi": "21:22", "faceoffWinningPctg": 0.510983,
                                            "gameTypeId": 2, "gameWinningGoals": 5,
                                            "gamesPlayed": 76, "goals": 32, "leagueAbbrev": "NHL", "otGoals": 1,
                                            "pim": 30, "plusMinus": 35,
                                            "points": 132, "powerPlayGoals": 7, "powerPlayPoints": 44,
                                            "season": 20232024, "sequence": 1,
                                            "shootingPctg": 0.121673, "shorthandedGoals": 1, "shorthandedPoints": 1,
                                            "shots": 263,
                                            "teamCommonName": {"default": "Oilers"},
                                            "teamName": {"default": "Edmonton Oilers", "fr": "Oilers d'Edmonton"},
                                            "teamPlaceNameWithPreposition": {"default": "Edmonton",
                                                                             "fr": "d'Edmonton"}},
                                           {"assists": 34, "avgToi": "23:02", "faceoffWinningPctg": 0.427729,
                                            "gameTypeId": 3, "gameWinningGoals": 1,
                                            "gamesPlayed": 25, "goals": 8, "leagueAbbrev": "NHL", "otGoals": 1,
                                            "pim": 10, "plusMinus": 12,
                                            "points": 42, "powerPlayGoals": 2, "powerPlayPoints": 17,
                                            "season": 20232024, "sequence": 1,
                                            "shootingPctg": 0.106667, "shorthandedGoals": 0, "shorthandedPoints": 0,
                                            "shots": 75,
                                            "teamCommonName": {"default": "Oilers"},
                                            "teamName": {"default": "Edmonton Oilers", "fr": "Oilers d'Edmonton"},
                                            "teamPlaceNameWithPreposition": {
                                                "default": "Edmonton", "fr": "d'Edmonton"}}],
                                       "awards": [
                                           {"trophy": {"default": "Art Ross Trophy", "fr": "Trophée Art Ross"},
                                            "seasons": [
                                                {"assists": 89, "blockedShots": 40, "gameTypeId": 2, "gamesPlayed": 82,
                                                 "goals": 64, "hits": 89,
                                                 "pim": 36, "plusMinus": 22, "points": 153, "seasonId": 20222023},
                                                {"assists": 79, "blockedShots": 26, "gameTypeId": 2, "gamesPlayed": 80,
                                                 "goals": 44, "hits": 75,
                                                 "pim": 45, "plusMinus": 28, "points": 123, "seasonId": 20212022},
                                                {"assists": 72, "blockedShots": 24, "gameTypeId": 2, "gamesPlayed": 56,
                                                 "goals": 33, "hits": 61,
                                                 "pim": 20, "plusMinus": 21, "points": 105, "seasonId": 20202021},
                                                {"assists": 67, "blockedShots": 46, "gameTypeId": 2, "gamesPlayed": 82,
                                                 "goals": 41, "hits": 28,
                                                 "pim": 26, "plusMinus": 20, "points": 108, "seasonId": 20172018},
                                                {"assists": 70, "blockedShots": 29, "gameTypeId": 2, "gamesPlayed": 82,
                                                 "goals": 30, "hits": 34,
                                                 "pim": 26, "plusMinus": 27, "points": 100, "seasonId": 20162017}]},
                                           {"trophy": {"default": "Conn Smythe Trophy", "fr": "Trophée Conn Smythe"},
                                            "seasons": [
                                                {"assists": 34, "blockedShots": 16, "gameTypeId": 3, "gamesPlayed": 25,
                                                 "goals": 8, "hits": 43,
                                                 "pim": 10, "plusMinus": 12, "points": 42, "seasonId": 20232024}]},
                                           {"trophy": {"default": "Hart Memorial Trophy", "fr": "Trophée Hart"},
                                            "seasons": [
                                                {"assists": 89, "blockedShots": 40, "gameTypeId": 2, "gamesPlayed": 82,
                                                 "goals": 64, "hits": 89,
                                                 "pim": 36, "plusMinus": 22, "points": 153, "seasonId": 20222023},
                                                {"assists": 72, "blockedShots": 24, "gameTypeId": 2, "gamesPlayed": 56,
                                                 "goals": 33, "hits": 61,
                                                 "pim": 20, "plusMinus": 21, "points": 105, "seasonId": 20202021},
                                                {"assists": 70, "blockedShots": 29, "gameTypeId": 2, "gamesPlayed": 82,
                                                 "goals": 30, "hits": 34,
                                                 "pim": 26, "plusMinus": 27, "points": 100, "seasonId": 20162017}]},
                                           {"trophy": {"default": "Maurice “Rocket” Richard Trophy"}, "seasons": [
                                               {"assists": 89, "blockedShots": 40, "gameTypeId": 2, "gamesPlayed": 82,
                                                "goals": 64, "hits": 89,
                                                "pim": 36, "plusMinus": 22, "points": 153, "seasonId": 20222023}]},
                                           {"trophy": {"default": "Ted Lindsay Award", "fr": "Trophée Ted Lindsay"},
                                            "seasons": [
                                                {"assists": 89, "blockedShots": 40, "gameTypeId": 2, "gamesPlayed": 82,
                                                 "goals": 64, "hits": 89,
                                                 "pim": 36, "plusMinus": 22, "points": 153, "seasonId": 20222023},
                                                {"assists": 72, "blockedShots": 24, "gameTypeId": 2, "gamesPlayed": 56,
                                                 "goals": 33, "hits": 61,
                                                 "pim": 20, "plusMinus": 21, "points": 105, "seasonId": 20202021},
                                                {"assists": 67, "blockedShots": 46, "gameTypeId": 2, "gamesPlayed": 82,
                                                 "goals": 41, "hits": 28,
                                                 "pim": 26, "plusMinus": 20, "points": 108, "seasonId": 20172018},
                                                {"assists": 70, "blockedShots": 29, "gameTypeId": 2, "gamesPlayed": 82,
                                                 "goals": 30, "hits": 34,
                                                 "pim": 26, "plusMinus": 27, "points": 100, "seasonId": 20162017}]}],
                                       }
    mock_http_client.get.return_value = mock_response

    player_data = player_client.get_player(1)
    assert player_data["player_id"] == 8478402
    assert player_data["first_name"] == "Connor"
    assert player_data["last_name"] == "McDavid"


def test_get_all_players(player_client, mock_http_client):
    mock_response = Mock()
    mock_response.json.return_value = [
        {
            "playerId": 1,
            "name": "First Last",
            "sweaterNumber": 10,
            "birthDate": "1990-01-01",
            "birthCity": "City",
            "birthCountry": "Country",
            "birthStateProvince": "State",
            "heightInCentimeters": 180,
            "weightInKilograms": 80,
            "positionCode": "Forward",
            "active": True,
            "teamId": 100,
            "teamAbbrev": "CT"
        }
    ]
    mock_http_client.get.return_value = mock_response

    players = player_client.get_all_players()
    assert len(players) == 1
    assert isinstance(players[0], Player)
    assert players[0].player_id == 1


def test_get_all_active_players(player_client, mock_http_client):
    mock_response = Mock()
    mock_response.json.return_value = [
        {
            "playerId": 1,
            "name": "First Last",
            "sweaterNumber": 10,
            "birthDate": "1990-01-01",
            "birthCity": "City",
            "birthCountry": "Country",
            "birthStateProvince": "State",
            "heightInCentimeters": 180,
            "weightInKilograms": 80,
            "positionCode": "Forward",
            "active": True,
            "teamId": 100,
            "teamAbbrev": "CT"
        }
    ]
    mock_http_client.get.return_value = mock_response

    players = player_client.get_all_active_players()
    assert len(players) == 1
    assert isinstance(players[0], Player)
    assert players[0].is_active is True


def test_get_all_inactive_players(player_client, mock_http_client):
    mock_response = Mock()
    mock_response.json.return_value = [
        {
            "playerId": 1,
            "name": "First Last",
            "sweaterNumber": 10,
            "birthDate": "1990-01-01",
            "birthCity": "City",
            "birthCountry": "Country",
            "birthStateProvince": "State",
            "heightInCentimeters": 180,
            "weightInKilograms": 80,
            "positionCode": "Forward",
            "active": False,
            "teamId": 100,
            "teamAbbrev": "CT"
        }
    ]
    mock_http_client.get.return_value = mock_response

    players = player_client.get_all_inactive_players()
    assert len(players) == 1
    assert isinstance(players[0], Player)
    assert players[0].is_active is False
