from pydantic import BaseModel, Field
from datetime import datetime
from typing import List, Dict


class Seeding(BaseModel):
    conference_abbrev: str = Field(description="Conference abbreviation")
    conference_home_sequence: int = Field(description="Conference home sequence")
    conference_l10_sequence: int = Field(description="Conference last 10 games sequence")
    conference_name: str = Field(description="Conference name")
    conference_road_sequence: int = Field(description="Conference road sequence")
    conference_sequence: int = Field(description="Conference sequence")
    date: datetime = Field(description="Date of the seeding")
    division_abbrev: str = Field(description="Division abbreviation")
    division_home_sequence: int = Field(description="Division home sequence")
    division_l10_sequence: int = Field(description="Division last 10 games sequence")
    division_name: str = Field(description="Division name")
    division_road_sequence: int = Field(description="Division road sequence")
    division_sequence: int = Field(description="Division sequence")
    game_type_id: int = Field(description="Game type ID")
    games_played: int = Field(description="Number of games played")
    goal_differential: int = Field(description="Goal differential")
    goal_differential_pctg: float = Field(description="Goal differential percentage")
    goal_against: int = Field(description="Goals against")
    goal_for: int = Field(description="Goals for")
    goals_for_pctg: float = Field(description="Goals for percentage")
    home_games_played: int = Field(description="Number of home games played")
    home_goal_differential: int = Field(description="Home goal differential")
    home_goals_against: int = Field(description="Home goals against")
    home_goals_for: int = Field(description="Home goals for")
    home_losses: int = Field(description="Home losses")
    home_ot_losses: int = Field(description="Home overtime losses")
    home_points: int = Field(description="Home points")
    home_regulation_plus_ot_wins: int = Field(description="Home regulation plus overtime wins")
    home_regulation_wins: int = Field(description="Home regulation wins")
    home_ties: int = Field(description="Home ties")
    home_wins: int = Field(description="Home wins")
    l10_games_played: int = Field(description="Last 10 games played")
    l10_goal_differential: int = Field(description="Last 10 games goal differential")
    l10_goals_against: int = Field(description="Last 10 games goals against")
    l10_goals_for: int = Field(description="Last 10 games goals for")
    l10_losses: int = Field(description="Last 10 games losses")
    l10_ot_losses: int = Field(description="Last 10 games overtime losses")
    l10_points: int = Field(description="Last 10 games points")
    l10_regulation_plus_ot_wins: int = Field(description="Last 10 games regulation plus overtime wins")
    l10_regulation_wins: int = Field(description="Last 10 games regulation wins")
    l10_ties: int = Field(description="Last 10 games ties")
    l10_wins: int = Field(description="Last 10 games wins")
    league_home_sequence: int = Field(description="League home sequence")
    league_l10_sequence: int = Field(description="League last 10 games sequence")
    league_road_sequence: int = Field(description="League road sequence")
    league_sequence: int = Field(description="League sequence")
    losses: int = Field(description="Total losses")
    ot_losses: int = Field(description="Overtime losses")
    place_name: Dict = Field(description="Place name")
    point_pctg: float = Field(description="Point percentage")
    points: int = Field(description="Total points")
    regulation_plus_ot_win_pctg: float = Field(description="Regulation plus overtime win percentage")
    regulation_plus_ot_wins: int = Field(description="Regulation plus overtime wins")
    regulation_win_pctg: float = Field(description="Regulation win percentage")
    regulation_wins: int = Field(description="Regulation wins")
    road_games_played: int = Field(description="Road games played")
    road_goal_differential: int = Field(description="Road goal differential")
    road_goals_against: int = Field(description="Road goals against")
    road_goals_for: int = Field(description="Road goals for")
    road_losses: int = Field(description="Road losses")
    road_ot_losses: int = Field(description="Road overtime losses")
    road_points: int = Field(description="Road points")
    road_regulation_plus_ot_wins: int = Field(description="Road regulation plus overtime wins")
    road_regulation_wins: int = Field(description="Road regulation wins")
    road_ties: int = Field(description="Road ties")
    road_wins: int = Field(description="Road wins")
    season_id: int = Field(description="Season ID")
    shootout_losses: int = Field(description="Shootout losses")
    shootout_wins: int = Field(description="Shootout wins")
    streak_code: str = Field(description="Streak code")
    streak_count: int = Field(description="Streak count")
    team_name: Dict = Field(description="Team name")
    team_common_name: Dict = Field(description="Team common name")
    team_abbrev: Dict = Field(description="Team abbreviation")
    team_logo: str = Field(description="Team logo URL")
    ties: int = Field(description="Total ties")
    waivers_sequence: int = Field(description="Waivers sequence")
    wildcard_sequence: int = Field(description="Wildcard sequence")
    win_pctg: float = Field(description="Win percentage")
    wins: int = Field(description="Total wins")
    clinch_indicator: str = Field(description="Clinch indicator", default="")


class Standings(BaseModel):
    date: datetime = Field(description="Date of the standings")
    seedings: List[Seeding] = Field(description="List of seedings")
    season: int = Field(description="Season", default=-1)

    @property
    def east_standings(self):
        return [s for s in self.seedings if s.conference_abbrev == "E"]

    @property
    def west_standings(self):
        return [s for s in self.seedings if s.conference_abbrev == "W"]
